export { default as CompanyOriented } from './company-oriented-product/CompanyOriented'
export { default as Course } from './course/Course'
export { default as Dashboard } from './dashboard/Dashboard'

export { default as Enrollment } from './enrollment/Enrollment'
export { default as Login } from './login/Login'
export { default as MathPhysics } from './math-physics/MathPhysics'
export { default as MobileProject } from './mobile-project/MobileProject'
export { default as Profile } from './profile/Profile'
export { default as Register } from './register/Register'
