export { default as Course } from './course/Course'
export { default as Dashboard } from './dashboard/Dashboard'
export { default as DetailCourse } from './detail-course/DetailCourse'
export { default as Enrolment } from './enrolment/Enrolment'
export { default as Login } from './login/Login'
export { default as Profile } from './profile/Profile'
export { default as Register } from './register/Register'
